// <auto-generated />
using System;
using GithubIntegrationServer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GithubIntegrationServer.Migrations
{
    [DbContext(typeof(GithubIntegrationServerContext))]
    partial class GithubIntegrationServerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GithubIntegrationServer.Models.AssignedTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GroupName");

                    b.Property<string>("TaskAssigned");

                    b.Property<bool>("TaskIsCompleted");

                    b.Property<string>("TaskName");

                    b.Property<DateTime>("TaskTimeStamp");

                    b.HasKey("TaskId");

                    b.ToTable("AssignedTask");
                });
#pragma warning restore 612, 618
        }
    }
}
