// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoadMapServer.Models;

namespace RoadMapServer.Migrations
{
    [DbContext(typeof(RoadMapServerContext))]
    [Migration("20180828060921_addedIdToMileStone")]
    partial class addedIdToMileStone
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RoadMapServer.Models.MileStone", b =>
                {
                    b.Property<int>("MileStoneId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("MileStoneIsCompleted");

                    b.Property<string>("MileStoneName");

                    b.Property<DateTime>("MileStoneTimeStamp");

                    b.Property<string>("RoadMapGroupName");

                    b.HasKey("MileStoneId");

                    b.HasIndex("RoadMapGroupName");

                    b.ToTable("MileStone");
                });

            modelBuilder.Entity("RoadMapServer.Models.RoadMap", b =>
                {
                    b.Property<string>("GroupName")
                        .ValueGeneratedOnAdd();

                    b.HasKey("GroupName");

                    b.ToTable("RoadMap");
                });

            modelBuilder.Entity("RoadMapServer.Models.MileStone", b =>
                {
                    b.HasOne("RoadMapServer.Models.RoadMap")
                        .WithMany("MileStones")
                        .HasForeignKey("RoadMapGroupName");
                });
#pragma warning restore 612, 618
        }
    }
}
